#include <iostream>
#include <vector>
#include <exception>
#include <cmath>
#include <algorithm>
#include <functional>
#include <numeric>


using namespace std;

int main(int argc, char** argv)
{
    try
    {
        //Go!
    }
    catch (std::exception & e)
    {
        cerr << "unexpected exception:" << e.what() << endl;
    }
    

    return 0;
}
